# Generated by Django 3.1.4 on 2020-12-17 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifsc', models.CharField(max_length=60)),
                ('bank_id', models.IntegerField()),
                ('branch', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=60)),
                ('state', models.CharField(max_length=60)),
            ],
        ),
    ]
