# Generated by Django 3.1.4 on 2020-12-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bankdetails_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='bank_name',
            field=models.CharField(default='Central Bank Of India', max_length=100),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='branch',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
